
create table emergency_contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  phone text not null,
  created_at timestamptz default now()
);

alter table emergency_contacts enable row level security;

create policy "Users can view their own emergency contacts."
  on emergency_contacts for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own emergency contacts."
  on emergency_contacts for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own emergency contacts."
  on emergency_contacts for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own emergency contacts."
  on emergency_contacts for delete
  using ( auth.uid() = user_id );
